### ISSUE TITLE
Contrails don't appear when having collisions

### ISSUE THREAD

**Issue by Kevin4e** [xan1242/NFSMW_XenonEffects#3]
When contrails are present and I'm having even weak collisions (weak meaning hitting road signs that don't generate long sparks) they keep disappearing even though I'm at a higher speed than necessary for the contrails to appear (+100Km/ h).

So basically you can't see the contrails and the sparks at the same time in any way.

I can't share a clip but I think that the issue is clear.

**Comment by xan1242** [comment]
https://github.com/xan1242/NFSMW_XenonEffects/blob/master/dllmain.cpp#L7

Known issue and a bug carried over from Carbon.

The reason it doesn't happen in Carbon is because it handles emitter spawning seemingly a bit slower than MW.

This only happens if you use high rates. Contrails do not disappear for me using the stock settings. (30FPS Contrails, 60FPS sparks)

**Comment by Kevin4e** [comment]
Thank you for the answer.
