### ISSUE TITLE
Sparks

### ISSUE THREAD

**Issue by nasiftanjim** [xan1242/NFSMW_XenonEffects#5]
Sparks in-game look very different from the one in the screenshots, it is more less detailed, why?

**Comment by xan1242** [comment]
Did you follow the last 2 instructions as written in README?

- Make sure that texture filtering is turned on in video settings! Otherwise sparks will be drawn at wrong coordinates!
- In case you're using NextGenGraphics.asi, please enable `UseD3DDeviceTexture` in the .ini

Provide a screenshot as well. I don't know what "more less detailed" means.

**Comment by nasiftanjim** [comment]
![image](https://github.com/xan1242/NFSMW_XenonEffects/assets/67149197/63674a47-77a1-42d1-8ad5-fa7a202cb20d)
they both are turned on

**Comment by nasiftanjim** [comment]
![image](https://github.com/xan1242/NFSMW_XenonEffects/assets/67149197/29b59e9d-382a-4c1c-9c1f-d16710941ae5)
the trails are like contrails & have no textures

**Comment by xan1242** [comment]
Check these 3 things:

1. There should be a file in the GLOBAL folder called "XenonEffects.tpk". If it's not there, extract it from the release package and place it there
2. Check if the path is correctly configured in ini: `TexturePack = GLOBAL\XenonEffects.tpk`
3. If both things check out and are correct, enable `UseD3DDeviceTexture` in the ini

To me (judging by the motion blur) it looks like you're using NextGenGraphics.asi which can cause these issues. You really should enable `UseD3DDeviceTexture`.

**Comment by nasiftanjim** [comment]
yes they are all okay, but still the contrail looking sparks exist
